imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'MopaBootstrapBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        less:
            node: /usr/local/bin/node
            node_paths: [/opt/lessc/lib, /usr/local/lib/node_modules, /usr/lib/node_modules,]
            apply_to: "\.less$"
        cssrewrite: ~
        cssembed:
            jar: %kernel.root_dir%/Resources/java/cssembed-0.3.6.jar
            apply_to: "\.css$|\.less$"
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar
            apply_to: "\.css$"
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar


# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

mopa_bootstrap:
    menu: ~
    form: 
        collection:
            widget_remove_btn:
                icon: trash
            widget_add_btn:
                icon: plus-sign
    initializr:
        meta:
            title:        "MopaBootstrapBundle"
            description:  "This is the Sandbox Site"
            keywords:     "bootstrap getootstrap opabootstrap mopabootstrapbundle bootstrap bundle symfony2"
            author_name:  "phiamo"
            author_url:   "phiamo@googlemail.com"
            nofollow:     false
            noindex:      false
        dns_prefetch:
            - '//ajax.googleapis.com'
        google:
            wt: 'xxx'
            analytics: 'UA-xxxxxxx-xx'
        diagnostic_mode: false
